apiVersion: v1
groupNames:
- system:masters
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-12-04T13:28:24Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
  resourceVersion: "1394"
  selfLink: /oapi/v1/clusterrolebindings/cluster-admin
  uid: 013ce8ed-d8f7-11e7-8c47-b6fd3158f970
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pvinstaller
  namespace: default
- kind: ServiceAccount
  name: helm
  namespace: kube-system
- kind: User
  name: admin
- kind: SystemGroup
  name: system:masters
userNames:
- system:serviceaccount:default:pvinstaller
- system:serviceaccount:kube-system:helm
- admin
