kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "tiller-binding-{{.Values.team}}"
  namespace: "{{.Release.Namespace}}"
subjects:
- kind: ServiceAccount
  name: "tiller-{{.Values.team}}"
  namespace: "{{.Release.Namespace}}"
roleRef:
  kind: Role
  name: dev-team
  apiGroup: rbac.authorization.k8s.io
